service: s3-presigned-apigateway-lambda
frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: dev
  environment:
    BUCKET_NAME: ${self:service}-${self:provider.stage}-uploads
  iamRoleStatements:
    - Effect: Allow
      Action: s3:PutObject
      Resource:
        - arn:aws:s3:::${self:provider.environment.BUCKET_NAME}/*

functions:
  urlSigner:
    handler: src/urlSigner.handler
    memorySize: 128
    timeout: 5
    events:
      - httpApi:
          path: /generate-upload-url
          method: POST

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        OwnershipControls:
          Rules:
            - ObjectOwnership: BucketOwnerEnforced
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

